import type { Metadata } from "next";
import { Playfair_Display, Open_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";
import Footer from "./_components/Footer";
import { BookingProvider } from "@/context/booking";
import { FilterProvider } from "@/context/filter";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // Define the weights you want to use
  variable: "--font-playfair", // CSS variable for custom font
});

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // Define the weights you want to use
  variable: "--font-opensans", // CSS variable for custom font
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${playfair.variable} ${openSans.variable}`}>
      <body>
      <FilterProvider >
        <Navbar />
          <BookingProvider >   
              {children}
          </BookingProvider>
        </FilterProvider>
        <Footer />
      </body>
    </html>
  );
}
